### ISSUE TITLE
 [WARN] flood.lua | Resources/Server\Flood\flood.lua:1: module 'multiplayer' not found: no field package.preload['multiplayer']

### ISSUE THREAD

**Issue by saulienis** [vulcan-dev/BeamMP-FloodMod#9]
So, using zap-hosting to play around with some friends.
Can't seem to make it work.
The Server version should be up-to-date.

Some more errors i see:
`[3/4/2024 19:31:50] [WARN] main.lua | Resources/Server\Flood\main.lua:1: module 'multiplayer' not found:
no field package.preload['multiplayer']`
`[3/4/2024 19:31:50] [WARN] multiplayer.lua | Resources/Server\Flood\multiplayer.lua:1: attempt to index a nil value (global 'MP')`

**Comment by daniel-w0** [comment]
I've not used Zap-Hosting so I'm unsure as to why this could be, but it works for others, myself included. It's either an issue with the version you're using, or something else related to BeamMP or Zap. Also, are you using this version of the flood: https://github.com/vulcan-dev/BeamMP-FloodMod/tree/1.1.0 ? If not, then I recommend trying that one out.

**Comment by saulienis** [comment]
So regards the server version, you can see in the picture

![image](https://github.com/vulcan-dev/BeamMP-FloodMod/assets/52180748/371890f4-ce93-4744-9e48-353f0b759df5)

And the mod version, i was using the latest in official releases, not branches, will have to try that
![image](https://github.com/vulcan-dev/BeamMP-FloodMod/assets/52180748/3e8d6975-3365-41c5-969e-6b0cb2b3f269)

**Comment by saulienis** [comment]
Sadly, doesn't seem to help even with the branched version

**Comment by daniel-w0** [comment]
Interesting. I'm on the same server version.
Maybe it's an issue with the filesystem since it can't find "multiplayer.lua"? Maybe you can try testing it locally on your machine to validate it works there. And I recommend sticking with the `1.1.0` branch, there's some fixes and improvements. It's also not using deprecated game functions.

**Comment by saulienis** [comment]
I will give it a try later on.
I remembered something as well.
Ages ago, about a year or two, i testing out Cobalt on the same platform, and i had issues, and we found it it was due server framework.
It was not supporting Linux, do you think it could be similar here?

**Comment by daniel-w0** [comment]
> I will give it a try later on. I remembered something as well. Ages ago, about a year or two, i testing out Cobalt on the same platform, and i had issues, and we found it it was due server framework. It was not supporting Linux, do you think it could be similar here?

Sorry, completely forgot to respond to this yesterday. But yes, it might be a similar issue, especially since it's failing to find the include "multiplayer.lua". Something is wrong with the server, filesystem, or something else. If it was an actual issue, then I and everyone else would also be experiencing it.
